name: MineAssistEx
main: com.biscrat.minecraft.mineassistex.MineAssistEx
version: 0.2
commands:
   MineAssist:
      description: MineAssistEx command.
      usage: /<command> [ON/OFF/TOGGLE/RELOAD] <target>
